### ISSUE TITLE
SPI mode appears to be wrong

### ISSUE THREAD

**Issue by aasimon** [theMossCode/as5048#1]
According to the datasheet the SPI wire mode should be 1.
In mode 1 the clock polarity (CPOL) is 0.
Setting the SPI mode to include the SPI_MODE_CPOL corresponds to setting it to 1, which (in my usecase) produces a lot of checksum errors.
Removing SPI_MODE_CPOL from AS5048_SPI_OPERATION removes all checksum errors in my application.

I have verified this with a logic-analyser.

**Comment by theMossCode** [comment]
Hi, 
You are correct, CPOL should be 0. Thanks for pointing that out.
I have pushed the update.
